name: Waifus simp 💖
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Show my favorite waifus 😳
        uses: lowlighter/metrics@v3.28.0
        with:
          filename: metrics.plugin.anilist.waifus.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: retpop
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22
          plugin_anilist_shuffle: yes

      - name: Report failure
        if: failure()
        run: echo "Workflow failed! Please check the logs for details."
